# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - testingcalc

on:
  push:
    branches:
      - dependabot/pip/django-2.2.18
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Install Python dependencies
      run: |
        python -m venv env
        .\env\Scripts\activate
        pip install -r requirements.txt

    - name: Zip the application files
      run: Compress-Archive .\* app.zip

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testingcalc'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2cf44b552eca481bb225337976c3e1e4 }}
        package: '.\app.zip'